/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  TodoItem,
} from './models/todoItem';

export namespace Components {
  interface MyApp {}
  interface TodoApp {}
  interface TodoList {
    'todoItems': TodoItem[];
  }
  interface TodoListForm {
    'todoItemsLength': number;
  }
}

declare global {


  interface HTMLMyAppElement extends Components.MyApp, HTMLStencilElement {}
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };

  interface HTMLTodoAppElement extends Components.TodoApp, HTMLStencilElement {}
  var HTMLTodoAppElement: {
    prototype: HTMLTodoAppElement;
    new (): HTMLTodoAppElement;
  };

  interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {}
  var HTMLTodoListElement: {
    prototype: HTMLTodoListElement;
    new (): HTMLTodoListElement;
  };

  interface HTMLTodoListFormElement extends Components.TodoListForm, HTMLStencilElement {}
  var HTMLTodoListFormElement: {
    prototype: HTMLTodoListFormElement;
    new (): HTMLTodoListFormElement;
  };
  interface HTMLElementTagNameMap {
    'my-app': HTMLMyAppElement;
    'todo-app': HTMLTodoAppElement;
    'todo-list': HTMLTodoListElement;
    'todo-list-form': HTMLTodoListFormElement;
  }
}

declare namespace LocalJSX {
  interface MyApp {}
  interface TodoApp {}
  interface TodoList {
    'todoItems'?: TodoItem[];
  }
  interface TodoListForm {
    'onInputChange'?: (event: CustomEvent<any>) => void;
    'onSubmit'?: (event: CustomEvent<any>) => void;
    'todoItemsLength'?: number;
  }

  interface IntrinsicElements {
    'my-app': MyApp;
    'todo-app': TodoApp;
    'todo-list': TodoList;
    'todo-list-form': TodoListForm;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-app': LocalJSX.MyApp & JSXBase.HTMLAttributes<HTMLMyAppElement>;
      'todo-app': LocalJSX.TodoApp & JSXBase.HTMLAttributes<HTMLTodoAppElement>;
      'todo-list': LocalJSX.TodoList & JSXBase.HTMLAttributes<HTMLTodoListElement>;
      'todo-list-form': LocalJSX.TodoListForm & JSXBase.HTMLAttributes<HTMLTodoListFormElement>;
    }
  }
}


